DELETE http://localhost:3003/api/blogs/68d1195743edf5b555c7cc02
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RldHNzdGkxIiwiaWQiOiI2OGNmZWU0Yjc3ZTQxNGFiNzU4YzFkM2MiLCJpYXQiOjE3NTg1MzQwMjV9.SAQDVJz1WBBJEVFzWi1fD1d6s8AdtOFZiINPzm_B1as
//mluukkai
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2OGNmZDFlNzY3NjRmZmY5NzJlNDlmM2EiLCJpYXQiOjE3NTg1MzIyODJ9.XIzQzRtT7tOVfYurSDq9Xf5UmP3R1jwBBHRin8s_oWA